name: Collect Library Licenses

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions: {} # No permissions by default on workflow level

jobs:
  collect-licenses:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Collect library licenses
        uses: open-edge-platform/geti-ci/actions/collect-sbom-library@6fe3ccd4f702a56614487b4aa3a414c4fe5221bf
        with:
          path: .
