# Renovate configuration validator
#
# This workflow validates changes proposed into Renovate configuration file
# (.github/renovate.json5) and prevents non-valid configuration to be used by Renovate.
#
# Required Secrets:
# - None
#
# Automatically triggered on:
# - Pull requests to .github/renovate.json5.
#

name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

permissions: {} # No permissions by default on workflow level

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          disable-sudo: true
          disable-telemetry: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            releases.astral.sh:443

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:44.17.1@sha256:90759c92793143ae7db68cd14e690109d8ace3527e17c7d188c96a1ad628282e
          docker run --rm --entrypoint "renovate-config-validator" \
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
          ${RENOVATE_IMAGE} "/renovate.json5"
